services:
  django:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: "on-failure"
    volumes:
      - "./app:/app"
    env_file:
      - "./app/env/.env"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - "./app/env/.env"

volumes:
  postgres:
